apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: souma4/message:V2
        ports:
        - containerPort: 9010
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: souma4-configmap
              key: MESSAGE_APPLICATION_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: message
spec:
  selector:
    app: message
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010